### ISSUE TITLE
Error in Replicating Uncertainty Maps

### ISSUE THREAD

**Issue by x33rak** [Ephemeral182/UDR-S2Former_deraining#12]
I am getting an error when trying to extract the uncertainty map from the last layer of the model. The uncertainty map shows that everything is high uncertainty as shown in the figure below which is not the correct output. I was wondering if you may know why this is occurring. 

![image](https://github.com/user-attachments/assets/758c8efa-949d-46bc-b97e-a71e8b362200)

**Comment by Ephemeral182** [comment]
Hi, you should cancel the final activation function in self.var_conv_final to visualize the uncertainty map instead of directly utilizing self.var_conv_final.

**Comment by x33rak** [comment]
I see, the activation function layer is what I was visualizing. That fixed it. 

<img width="551" alt="image" src="https://github.com/user-attachments/assets/d9cbbd87-6e4c-4b62-af41-1bac02de6517">

**Comment by Ephemeral182** [comment]
That's  correct!

**Comment by x33rak** [comment]
Thank you!

**Comment by tanbuzheng** [comment]
Dear author, sorry to bother you. I have recently encountered the same issue. Could I ask whether the final ELU activation function should be removed during network training, or during testing/visualization?
