### ISSUE TITLE
Version of pytorch-lightning

### ISSUE THREAD

**Issue by cherrysherryplus** [Ephemeral182/UDR-S2Former_deraining#4]
Hi! It is a great and intersting work. But I am wondering the version of pytorch-lightning you used because I met some problem with the latest version (v2.x)

**Comment by Ephemeral182** [comment]
Hi, we train our model by PyTorch-lightning 1.8.0 previously, but I tested my model in latest version of PyTorch-lightning (v2.x) before I release my code. I think it's ok to use this code. Could you share your problems encountered?

**Comment by cherrysherryplus** [comment]
Thanks for your reply! I have run the code successfully after I commented the **`'logger': logger`** in [https://github.com/Ephemeral182/UDR-S2Former_deraining/blob/main/train.py#L226](https://github.com/Ephemeral182/UDR-S2Former_deraining/blob/main/train.py#L226).

---
Before that, the problem is shown as the following screenshot:
![image](https://github.com/Ephemeral182/UDR-S2Former_deraining/assets/40523189/e038261f-1e26-4036-aa60-6a0178dde38b)

**Comment by Ephemeral182** [comment]
Thank you for sharing!

**Comment by cherrysherryplus** [comment]
Hi! I have found one possible solution. The problem may come from the configuration of using `TensorBoardLogger` in `main.py`.

The original version ([L31](https://github.com/Ephemeral182/UDR-S2Former_deraining/blob/main/train.py#L31)-L32, [L226](https://github.com/Ephemeral182/UDR-S2Former_deraining/blob/main/train.py#L226)) is:
```python
from pytorch_lightning.loggers import WandbLogger,TensorBoardLogger
logger = TensorBoardLogger(r'tb_logs', name='udrs2former')
```
```python
trainer_defaults = {'devices':[1,2,3],'callbacks':[checkpoint_callback,lr_monitor],'logger':logger}
```

The first block may be removed and the second can be altered as follows:
```python
train_defaults = {
  # configs of device and callbacks goes here...
  'logger': {
      'class_path': 'lightning.pytorch.loggers.TensorBoardLogger',
      'init_args': {
          'save_dir': 'tb_logs',
          'name': 'udrs2former'
      }
  }
}
```

**Comment by Ephemeral182** [comment]
This may be caused by the updated version. This is indeed a good solution. Thank you.

**Comment by Madeline-hyh** [comment]
Hello, I have the same problem, and when I change the logger, I have another problem, can you please see it? thanks! 
![image](https://github.com/Ephemeral182/UDR-S2Former_deraining/assets/72843081/6bcac252-dfaa-4ffb-ae58-38b0086ac430)

**Comment by Feecuin** [comment]
> 你好，我也有同样的问题，当我更换记录器时，我又遇到了另一个问题，你能看看吗？谢谢！ ![图像](https://private-user-images.githubusercontent.com/72843081/294811599-6bcac252-dfaa-4ffb-ae58-38b0086ac430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjYyNDcsIm5iZiI6MTcxMjAyNTk0NywicGF0aCI6Ii83Mjg0MzA4MS8yOTQ4MTE1OTktNmJjYWMyNTItZGZhYS00ZmZiLWFlNTgtMzhiMDA4NmFjNDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAyNDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZDI5MjlmYTMzMWQyMDk3NDc1MmYxZjE5ZTFkZWM2ODFiN2RkODVlZDcxMjgzNmZiNGE1ZTJhNzExZjFjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sbb0ROsm8q_LQ1wPO-YxXinP3H-xVLvFOEtUVLNv-nA)

你好，请问你解决了这个问题了吗？

**Comment by Madeline-hyh** [comment]
没有~

**Comment by Feecuin** [comment]
> 没有~

我也是这个问题，我打算降一下pytorch版本了

**Comment by Madeline-hyh** [comment]
可以试试~

**Comment by cherrysherryplus** [comment]
> 可以试试~



> Hello, I have the same problem, and when I change the logger, I have another problem, can you please see it? thanks! ![image](https://private-user-images.githubusercontent.com/72843081/294811599-6bcac252-dfaa-4ffb-ae58-38b0086ac430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDkxNzUsIm5iZiI6MTcxMjA0ODg3NSwicGF0aCI6Ii83Mjg0MzA4MS8yOTQ4MTE1OTktNmJjYWMyNTItZGZhYS00ZmZiLWFlNTgtMzhiMDA4NmFjNDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA5MDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDYyY2M3NDM2YWM5NmY3YTgyZjMyYWE3NDFjNDQ1NTg4YzNlNjNhZTVmOTc1YWIwZWVjODVmOWUxZTIyOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q_TNjKFJhv628RwkyZq97Af9uDExrJmzi4ZRrSEqn3c)

感觉2.x版本的lightning的话，可以试试用jsonargparse里的lazyinstance类包裹一下TensorBoardLogger
