### ISSUE TITLE
Regarding the issue with testing

### ISSUE THREAD

**Issue by ghost** [Ephemeral182/UDR-S2Former_deraining#5]
Hello, thank you for your excellent work.
However, there are some issues with the provided code that have troubled me：
The saved model cannot be used when loaded in the test. 

I would be grateful if you could provide me with the relevant assistance.

**Comment by Ephemeral182** [comment]
Hi, we utilize PyTorch_lightning for training, where checkpoints are saved with other hyperparameters in ***.ckpt** file. The underlying code like pytorch_lightning makes it a bit difficult for some people. So, you need to first take out the checkpoint of the model from the **.ckpt** file (just like my **.pth** checkpoints). Here is the code for this operation:
```
ckpt = torch.load('your ***.ckpt**')
new_state_dict = OrderedDict()
    for k in ckpt['state_dict']:
                    print(k)
                    if k[:6] != 'model.':
                        continue
                    name = k[6:]
                    new_state_dict[name] = ckpt['state_dict'][k]
**your model**.load_state_dict(new_state_dict,strict=False)
```

**Comment by Owen718** [comment]
> The code you provided is too poor. The saved model cannot be used when loaded in the test, and the original training code is also very complicated and unclear. Please provide a well-improved and readable code.

Hello Li Zixuan, I suggest you learn how to communicate politely online. Also, I came to know your name after looking at the Python experiment you shared in the open source community.

**Comment by Owen718** [comment]
> The code you provided is too poor. The saved model cannot be used when loaded in the test, and the original training code is also very complicated and unclear. Please provide a well-improved and readable code.

Additionally, in PyTorchLightning, the trainer supports direct validation through the `trainer.validate` function. I recommend that you first consult the PyTorchLightning documentation for more details.

**Comment by ghost** [comment]
@Owen718 
Hello, I have already solved the problem using my own method. Since the training code can load .ckpt files, I had to forcibly add "--trainer.num_sanity_val_steps 500" in the training file code to complete the testing.

However, the fact is that the test code provided by the author cannot directly use the .ckpt files saved during training. I just raised my issue and expressed doubts about the explanation of the code. Of course, all the learning files in my repository are open for review, and I would not be displeased with you knowing my real information.

**Comment by ghost** [comment]
@Owen718 Additionally, if you think there is any impoliteness in my question, I am willing to modify it to make you feel comfortable. However, the issues with the code are an undeniable fact. You cannot assume that the readers are facing problems due to unfamiliarity with PyTorchLightning.

**Comment by Owen718** [comment]
> @Owen718 Additionally, if you think there is any impoliteness in my question, I am willing to modify it to make you feel comfortable. However, the issues with the code are an undeniable fact. You cannot assume that the readers are facing problems due to unfamiliarity with PyTorchLightning.

You're right, we can't guarantee that everyone who uses our code has the same level of expertise as we do.

Sharing academic work in open source is to increase its impact and benefit the community, and it certainly doesn't have the robustness of production-level code. I hope that your team can make as much of your work open source as possible in the future. Thank you.

**Comment by ghost** [comment]
@Owen718 
Even so, your response still does not acknowledge the existence of issues with the testing aspect of the code, which leaves me confused. Furthermore, the content of your reply does not seem as polite and respectful as you mentioned earlier. Bringing up topics unrelated to this work and discussion only causes discomfort. Since I have already resolved my issue, I see no need for further discussion. I wish you success in your future work.

**Comment by Owen718** [comment]
<img width="680" alt="image" src="https://github.com/Ephemeral182/UDR-S2Former_deraining/assets/57895293/1cd844a1-fa1a-497a-91e1-53db09035176">

I don’t need to show respect to someone who speaks to strangers in such a tone.

**Comment by Owen718** [comment]
> <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/57895293/293177001-1cd844a1-fa1a-497a-91e1-53db09035176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTU0MjksIm5iZiI6MTcwMzc1NTEyOSwicGF0aCI6Ii81Nzg5NTI5My8yOTMxNzcwMDEtMWNkODQ0YTEtZmExYS00OTdhLTkxZTEtNTNkYjA5MDM1MTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5MTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZWE0NmViMzRiZjBkY2FjOGE3MzI5YWYxOGUwYTMyYjVkYzc4ODViOGQ0YzQ0ZTQyZjVhZDBhMzJmMzI1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o4gi7fP3no51shYg7ymhW_TNLy3CIqGkgE1MEXdoG70">
> I don’t need to show respect to someone who speaks to strangers in such a tone.

<img width="623" alt="image" src="https://github.com/Ephemeral182/UDR-S2Former_deraining/assets/57895293/a42d86ab-fbfe-464f-a6a6-8229bd85cdbb">
